### ISSUE TITLE
SSH command to connect properly and/or be more clear

### ISSUE THREAD

**Issue by elliottmangham** [garethmidwood/cdev#17]
Currently `cdev env:ssh` provides a command to run manually and appears as though it has connected, however does not give any ability. This means the user must then exit the SSH and then copy/paste the string provided in order to gain SSH access.

It would be good if this was to actually connect properly/run the command. If this isn't possible, it would be great to make this more clear.

**Comment by garethmidwood** [comment]
This is done in https://github.com/garethmidwood/cdev/pull/21
