### ISSUE TITLE
Command to automatically install / set up boilerplate

### ISSUE THREAD

**Issue by elliottmangham** [garethmidwood/cdev#18]
Create a command, such as `cdev site:create` which would display the following questions:

1. What CMS boilerplate would you like to install? _[WordPress]/[Magento]/[Drupal]_
2. What version of the CMS would you like to install? _[...]_
3. Would you like to run Composer? _[Y]/[N]_
4. Would you like to install an `.env` file with default varialbes for PHP variables? _[Y]/[N]_
5. Would you like to install Front-End Tools? _[Y]/[N]_

**Breakdown:**
1. Clones the boilerplate git repository for the chosen CMS
2. WordPress, Mage1/2 or Drupal 7/8
3. Runs `composer install` followed by `composer update` in relevant directories
4. Creates and populates an `.env` file within correct directory (such as default database details)
5. Clones the front-end theme tools directory within the appropriate theme directory, and runs `pnpm install`, `npm install` or `yarn`. Also replace vhost URL in `gulpfile.js` (cloned) with the URL set in `cdev configure`

It would be good if at the end of running `cdev configure` you are then given the option to run this command.

**Comment by garethmidwood** [comment]
https://github.com/garethmidwood/cdev/pull/24

**Comment by elliottmangham** [comment]
Pull request #24 has been merged with master. This still requires work and discussions, so will remain open for now.

**Comment by elliottmangham** [comment]
Will create a new ticket to address the creation of environment variables and close this ticket.
