### ISSUE TITLE
Drush container doesn't work with Cdev

### ISSUE THREAD

**Issue by michall05** [garethmidwood/cdev#27]

**Comment by garethmidwood** [comment]
I'm told that drush should be installed with composer, which means that the container should not be used. I'm going to close this ticket on that basis.

A ticket may potentially be needed on the Drupal 7/8 framework repositories if the `cache:clear` (and other) commands do not work as-is. Here are the repo links:
https://github.com/creode/cdev-framework-drupal7
https://github.com/creode/cdev-framework-drupal8
