### ISSUE TITLE
Docker Sync does not stop running when `cdev env:stop`

### ISSUE THREAD

**Issue by elliottmangham** [garethmidwood/cdev#5]
See error when running `cdev env:start` after running `cdev env:stop`.
This issue is meaning I must manually stop Docker Sync (by running `docker-sync stop`) or nuking my environment (`cdev env:nuke`), which at the moment means the database is wiped. While this is okay in most CMS platforms, it is no good for WordPress as many site changes heavily rely on an up-to-date database.

See screenshot of error below:
![image](https://user-images.githubusercontent.com/12933804/29167847-0cfc1ee4-7dc4-11e7-96fe-3e751acf2605.png)

**Comment by creode-jeb** [comment]
Gareth has added a fix for this. 
You can see the code change [here](https://github.com/garethmidwood/cdev/pull/12)
