### ISSUE TITLE
Add a new plugin update command

### ISSUE THREAD

**Issue by jamiesykescreode** [garethmidwood/cdev#62]
Currently when a plugin for cdev is updated there isn't an update command to take the latest version of the plugin. This should be added in order to make it easier to update plugins.

If you give the name of a valid plugin to the command it will run an update for that specific plugin. If not we should just update all plugins.

```composer update```

Plugins are stored in:

```~/.cdev/plugins/```

**Comment by garethmidwood** [comment]
Looks like I did this back in December last year. Closing.
