### ISSUE TITLE
Wordpress composer sites

### ISSUE THREAD

**Issue by alexcreode** [garethmidwood/cdev#64]
Wordpress composer sites actually get deployed through /src/web/

currently you have to run open a new tab and run

$ cdev env:ssh --user=root
$ apt-get update
$ apt-get install vim
$ vi /etc/apache2/sites-available/000-default.conf

Once inside vim you are required to change the line

DocumentRoot /var/www/html 

to 

DocumentRoot /var/www/html/web

then 

:wq to exist vim

$ service apache2 reload

This isn't the end of the world but I would very much appreciate not needing to go through these steps.

I would like it if during cdev configure there was an option of "wordpress composer" amongst the "Framework:" choices.

I hope this all makes sense

**Comment by garethmidwood** [comment]
I've resolved this in the docker environment plugin, here's a link to the PR - https://github.com/creode/cdev-environment-docker/pull/12/files

You're now asked if you'd like to use a custom webroot, and if you choose to, the default apache config files are copied to a local `config/apache` dir (config sits alongside the cdev dir) and the webroot updated to include the custom dir
