### ISSUE TITLE
Deprecation warning: Your package name cdev-plugins is invalid

### ISSUE THREAD

**Issue by michall05** [garethmidwood/cdev#72]
Deprecation warning: Your package name cdev-plugins is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.

**Comment by garethmidwood** [comment]
If you've already got a plugins composer.json, here's a command to update the composer package name

```sed -i -e 's/cdev-plugins/cdev\/plugins/g' ~/.cdev/plugins/composer.json```
