### ISSUE TITLE
Configuration defaults

### ISSUE THREAD

**Issue by elliottmangham** [garethmidwood/cdev#8]
At the moment all options are set as `[n]` when running `cdev configure`.
I suggest setting the defaults, i.e. PHP and MySql to `[y]`...etc.

I also recommend similar to #19 _[Closed]_ that defaults can optionally be set up globally.

**Comment by garethmidwood** [comment]
Defaults are set in PR https://github.com/garethmidwood/cdev/pull/35

MySQL, PHP, Mailcatcher = On
Redis, Drush = Off

It's not currently possible to set global options, as the environment is only chosen for a project. To be able to set global options we would have to run through each potential environment type and ask for defaults for each container (or the environment equivalent).
