### ISSUE TITLE
Command to set PHP environment variables

### ISSUE THREAD

**Issue by elliottmangham** [garethmidwood/cdev#9]
Ability to create PHP environment variables (if PHP is installed during `configure`). This will either be during `configure`, `site:create`, and/or with a unique command.

Before deciding variables, the user will be prompted with an option of how they want to store these environment variables. This may be either:

1. Store in `cdev/docker-compose.yml` (Docker Compose)
2. Store in `src/.env` (Environment file, recommended with Creode Boilerplate)
3. Store in `~/.bash_profile` (local Bash file)

**Comment by garethmidwood** [comment]
The request makes sense but the last 2 options don't. We should put the variables into `cdev/docker-compose.yml` so that they're part of the environment when it's booted

**Comment by garethmidwood** [comment]
This should now be in the docker environment plugin repo - https://github.com/creode/cdev-environment-docker/issues
